version: '3.8'

services:
  readerific:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Maps container port 80 to host port 8000
    volumes:
      - ./:/usr/share/nginx/html  # For development: maps local files to container
    networks:
      - app-network  # Add this to your existing network if needed

networks:
  app-network:
    name: app-network  # You can change this to match your existing network name
    external: true  # Set to true if the network already exists from other services
