version: '3.8'

services:
  readerific:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    networks:
      - readerific-net

networks:
  readerific-net:
